[package]
name = "quicssh-rs"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["oowl <ouyangjun1999@gmail.com>"]
description = "A simple ssh server based on quic protocol"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
quinn = "0.9.3"
tokio = { version = "1.28.0", features = ["full"] }
url = "2.3.1"
rustls = { version = "0.20.6", features = ["quic", "dangerous_configuration"] }
rustls-pemfile = "1.0.2"
rcgen = "0.10.0"
log = { version = "0.4", features = ["std", "serde"] }
env_logger = "0.11.1"
